Repository googleapis/java-os-login, pull requests merged in 2020-06, with the labels that each got.

#165 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#157 fix: restore GAPIC v2 retry configs
  google-cloud-os-login/src/main/java/com/google/cloud/oslogin/v1/OsLoginServiceClient.java
  google-cloud-os-login/src/main/java/com/google/cloud/oslogin/v1/OsLoginServiceSettings.java
  google-cloud-os-login/src/main/java/com/google/cloud/oslogin/v1/stub/GrpcOsLoginServiceStub.java
  google-cloud-os-login/src/main/java/com/google/cloud/oslogin/v1/stub/OsLoginServiceStub.java
  google-cloud-os-login/src/main/java/com/google/cloud/oslogin/v1/stub/OsLoginServiceStubSettings.java
  google-cloud-os-login/src/test/java/com/google/cloud/oslogin/v1/OsLoginServiceClientTest.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#168 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#167 chore: regenerate with updated protoc
  proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/common/OsLoginProto.java
  proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/v1/DeletePosixAccountRequest.java
  proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/v1/DeleteSshPublicKeyRequest.java
  proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/v1/GetLoginProfileRequest.java
  proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/v1/GetSshPublicKeyRequest.java
  proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/v1/ImportSshPublicKeyRequest.java
  proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/v1/ImportSshPublicKeyResponse.java
  proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/v1/LoginProfile.java
  proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/v1/UpdateSshPublicKeyRequest.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#170 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#172 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#176 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#177 fix: migrate oslogin/v1 to grpc_service_config
  google-cloud-os-login/src/main/java/com/google/cloud/oslogin/v1/OsLoginServiceClient.java
  google-cloud-os-login/src/main/java/com/google/cloud/oslogin/v1/OsLoginServiceSettings.java
  google-cloud-os-login/src/main/java/com/google/cloud/oslogin/v1/stub/GrpcOsLoginServiceStub.java
  google-cloud-os-login/src/main/java/com/google/cloud/oslogin/v1/stub/OsLoginServiceStub.java
  google-cloud-os-login/src/main/java/com/google/cloud/oslogin/v1/stub/OsLoginServiceStubSettings.java
  google-cloud-os-login/src/test/java/com/google/cloud/oslogin/v1/OsLoginServiceClientTest.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#181 ci: switch to secret manager for sample/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#185 chore: update README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#186 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-os-login/pom.xml
  grpc-google-cloud-os-login-v1/pom.xml
  pom.xml
  proto-google-cloud-os-login-v1/pom.xml
Labels: cla: yes

#197 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
