Repository googleapis/java-os-login, pull requests merged in 2021-09, with the labels that each got.

#543 build(java): update renovate config to mark conformance tests as a test commit type
  renovate.json
  synth.metadata
Labels: cla: yes, api: oslogin, automerge, context: full

#542 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: oslogin, automerge

#545 chore(java): install maven 3.8.1 at runtime
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, api: oslogin, context: full

#554 chore: remove readme autosynth config
  .github/readme/synth.metadata/synth.metadata
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: cla: yes, api: oslogin, automerge

#566 chore: make owlbot check required
  .github/sync-repo-settings.yaml
  README.md
Labels: cla: yes, api: oslogin

#560 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: cla: yes, api: oslogin, automerge

#570 chore: change branch master to main in sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: oslogin, automerge
