Repository googleapis/java-os-login, pull requests merged in 2021-05, with the labels that each got.

#439 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: oslogin, automerge, cla: yes

#440 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: oslogin, automerge, cla: yes, context: none

#441 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: oslogin, automerge, cla: yes, context: full

#443 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: oslogin, automerge, cla: yes

#445 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: oslogin, automerge, cla: yes

#446 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: oslogin, automerge, cla: yes, context: full

#451 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: oslogin, automerge, cla: yes

#453 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: oslogin, automerge, cla: yes, context: full

#459 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: oslogin, automerge, cla: yes

#452 chore: release gapic-generator-java v1.0.5
  google-cloud-os-login/src/main/java/com/google/cloud/oslogin/v1/OsLoginServiceClient.java
  google-cloud-os-login/src/test/java/com/google/cloud/oslogin/v1/OsLoginServiceClientTest.java
  synth.metadata
Labels: api: oslogin, automerge, cla: yes, context: full

#455 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: oslogin, automerge, cla: yes, context: full

#461 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: oslogin, cla: yes, context: full

#464 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: oslogin, automerge, cla: yes
