Repository googleapis/java-os-login, pull requests merged in 2021-02, with the labels that each got.

#322 chore: migrate to microgenerator
  google-cloud-os-login/src/main/java/com/google/cloud/oslogin/v1/OsLoginServiceClient.java
  google-cloud-os-login/src/main/java/com/google/cloud/oslogin/v1/OsLoginServiceSettings.java
  google-cloud-os-login/src/main/java/com/google/cloud/oslogin/v1/package-info.java
  google-cloud-os-login/src/main/java/com/google/cloud/oslogin/v1/stub/GrpcOsLoginServiceCallableFactory.java
  google-cloud-os-login/src/main/java/com/google/cloud/oslogin/v1/stub/GrpcOsLoginServiceStub.java
  google-cloud-os-login/src/main/java/com/google/cloud/oslogin/v1/stub/OsLoginServiceStub.java
  google-cloud-os-login/src/main/java/com/google/cloud/oslogin/v1/stub/OsLoginServiceStubSettings.java
  google-cloud-os-login/src/test/java/com/google/cloud/oslogin/v1/MockOsLoginService.java
  google-cloud-os-login/src/test/java/com/google/cloud/oslogin/v1/MockOsLoginServiceImpl.java
  google-cloud-os-login/src/test/java/com/google/cloud/oslogin/v1/OsLoginServiceClientTest.java
  proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/common/PosixAccountName.java
  proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/common/SshPublicKeyName.java
  proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/common/UserName.java
  proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/v1/PosixAccountName.java
  proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/v1/SshPublicKeyName.java
  proto-google-cloud-os-login-v1/src/main/java/com/google/cloud/oslogin/v1/UserName.java
  synth.metadata
  synth.py
Labels: api: oslogin, automerge, cla: yes, context: full

#351 chore: Re-generated to pick up changes from synthtool.
  .github/workflows/ci.yaml
  .kokoro/linkage-monitor.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: oslogin, cla: yes, context: partial

#357 chore: update synth.py
  synth.py
Labels: api: oslogin, automerge, cla: yes

#362 chore: Re-generated to pick up changes from synthtool
  .github/workflows/auto-release.yaml
  .kokoro/release/publish_javadoc11.cfg
  LICENSE
  google-cloud-os-login/src/main/java/com/google/cloud/oslogin/v1/OsLoginServiceClient.java
  synth.metadata
Labels: api: oslogin, cla: yes, context: partial

#363 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: oslogin, automerge, cla: yes

#361 chore: Re-generated to pick up changes from googleapis
  google-cloud-os-login/src/main/java/com/google/cloud/oslogin/v1/stub/GrpcOsLoginServiceCallableFactory.java
  google-cloud-os-login/src/main/java/com/google/cloud/oslogin/v1/stub/OsLoginServiceStub.java
  google-cloud-os-login/src/main/java/com/google/cloud/oslogin/v1/stub/OsLoginServiceStubSettings.java
  synth.metadata
Labels: api: oslogin, automerge, cla: yes, context: partial

#365 feat: generate sample code in the Java microgenerator
  google-cloud-os-login/src/main/java/com/google/cloud/oslogin/v1/OsLoginServiceClient.java
  google-cloud-os-login/src/main/java/com/google/cloud/oslogin/v1/package-info.java
  synth.metadata
Labels: api: oslogin, automerge, cla: yes, context: partial

#368 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: oslogin, automerge, cla: yes

#369 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: oslogin, automerge, cla: yes

#372 ci: linkage monitor CI job to use build.sh
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: oslogin, automerge, cla: yes, context: full

#371 chore: update gapic-generator-java to 0.0.20
  google-cloud-os-login/src/main/java/com/google/cloud/oslogin/v1/stub/GrpcOsLoginServiceStub.java
  google-cloud-os-login/src/test/java/com/google/cloud/oslogin/v1/MockOsLoginServiceImpl.java
  synth.metadata
Labels: api: oslogin, automerge, cla: yes, context: full

#373 chore: update cloud-rad buckets
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: oslogin, automerge, cla: yes, context: full

#374 build: skip Maven download logs
  .kokoro/build.sh
  synth.metadata
Labels: api: oslogin, automerge, cla: yes, context: full

#375 build: reduce download junk in log files
  .kokoro/build.sh
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: oslogin, automerge, cla: yes, context: full

#377 chore: release gapic-generator-java v0.0.21 with gapic_metadata.json support
  google-cloud-os-login/src/main/java/com/google/cloud/oslogin/v1/gapic_metadata.json
  synth.metadata
Labels: api: oslogin, automerge, cla: yes, context: full

#380 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: oslogin, automerge, cla: yes

#381 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: oslogin, automerge, cla: yes

#383 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: oslogin, automerge, cla: yes

#389 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: oslogin, automerge, cla: yes
