Repository googleapis/java-os-login, pull requests merged in 2021-08, with the labels that each got.

#503 chore: remove java 7 units check
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, api: oslogin, automerge, context: full

#512 chore: remove java7 units check from required checks in master
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: oslogin, automerge

#509 feat!: release gapic-generator-java v2.0.0
  google-cloud-os-login/src/main/java/com/google/cloud/oslogin/v1/OsLoginServiceSettings.java
  google-cloud-os-login/src/main/java/com/google/cloud/oslogin/v1/stub/GrpcOsLoginServiceStub.java
  google-cloud-os-login/src/main/java/com/google/cloud/oslogin/v1/stub/OsLoginServiceStubSettings.java
  synth.metadata
Labels: cla: yes, api: oslogin, automerge, context: full

#518 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: oslogin, automerge

#520 build(java): use ENABLE_FLAKYBOT env variable
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  synth.metadata
Labels: kokoro:force-run, cla: yes, api: oslogin, automerge, context: full

#522 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: oslogin, automerge

#525 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: oslogin, automerge

#526 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: oslogin, automerge

#529 ci: removing linkage-monitor from the required checks
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: oslogin, automerge

#532 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: oslogin, automerge

#539 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: oslogin, automerge

#534 ci: removing linkage-monitor from the required checks
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, api: oslogin, automerge, context: full

#523 chore: update gapic-generator-java version to 2.1.0
  google-cloud-os-login/src/main/java/com/google/cloud/oslogin/v1/stub/OsLoginServiceStubSettings.java
  synth.metadata
Labels: cla: yes, api: oslogin, automerge, context: full
